{
 "title": "Cluster",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Cluster",
    "query": {
     "query": "label_values(ceph_active_pgs, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_health_status{job=\"$job\", cluster=\"ceph\"}"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_osd_total_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_osd_total_used_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Used %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_osd_total_used_bytes{job=\"$job\"}/ceph_osd_total_bytes{job=\"$job\"}*100"
    }
   ]
  },
  {
   "title": "Mon",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_mon_quorum_status{job=\"$job\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up{job=\"$job\", cluster=\"ceph\"})"
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_in{job=\"$job\", cluster=\"ceph\"})"
    }
   ]
  },
  {
   "title": "pools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_pool_bytes_used{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average Monitor Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_paxos_refresh_latency_sum{job=\"$job\"}/ceph_paxos_refresh_latency_count{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average OSD Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average OSD Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_pg_active{job=\"$job\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "ceph_pg_clean{job=\"$job\"}",
     "legendFormat": "Clean"
    },
    {
     "expr": "ceph_pg_peering{job=\"$job\"}",
     "legendFormat": "Peering"
    },
    {
     "expr": "ceph_pg_degraded{job=\"$job\"}",
     "legendFormat": "Degraded"
    },
    {
     "expr": "ceph_pg_stale{job=\"$job\"}",
     "legendFormat": "Stale"
    },
    {
     "expr": "ceph_unclean_pgs{job=\"$job\"}",
     "legendFormat": "Unclean"
    },
    {
     "expr": "ceph_pg_undersized{job=\"$job\"}",
     "legendFormat": "Undersized"
    },
    {
     "expr": "ceph_pg_incomplete{job=\"$job\"}",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "ceph_pg_forced_backfill{job=\"$job\"}",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "ceph_pg_inconsistent{job=\"$job\"}",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "ceph_pg_forced_recovery{job=\"$job\"}",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "ceph_pg_creating{job=\"$job\"}",
     "legendFormat": "Creating"
    },
    {
     "expr": "ceph_pg_wait_backfill{job=\"$job\"}",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "ceph_pg_deep{job=\"$job\"}",
     "legendFormat": "Deep"
    },
    {
     "expr": "ceph_pg_scrubbing{job=\"$job\"}",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "ceph_pg_recovering{job=\"$job\"}",
     "legendFormat": "Recovering"
    },
    {
     "expr": "ceph_pg_repair{job=\"$job\"}",
     "legendFormat": "Repair"
    },
    {
     "expr": "ceph_pg_down{job=\"$job\"}",
     "legendFormat": "Down"
    },
    {
     "expr": "ceph_pg_peered{job=\"$job\"}",
     "legendFormat": "Peered"
    },
    {
     "expr": "ceph_pg_backfill{job=\"$job\"}",
     "legendFormat": "Backfill"
    },
    {
     "expr": "ceph_pg_remapped{job=\"$job\"}",
     "legendFormat": "Remapped"
    },
    {
     "expr": "ceph_pg_backfill_toofull{job=\"$job\"}",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_osds", "legendFormat": "Total" },
    { "expr": "ceph_osds_in", "legendFormat": "In" },
    { "expr": "ceph_osds - ceph_osds_in", "legendFormat": "Out" },
    {
     "expr": "sum(ceph_osd_up{cluster=\"$job\"})",
     "legendFormat": "Up"
    },
    { "expr": "ceph_osds_down", "legendFormat": "Down" }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{job=\"$job\"}[$__interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{job=\"$job\"}[$__interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_rw_in_bytes{job=\"$job\"}[$__interval]))",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "OSD Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000*sum(increase(ceph_osd_op_r_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_r_latency_count{job=\"$job\"}[$__rate_interval])),1)",
     "legendFormat": "read"
    },
    {
     "expr": "1000*sum(increase(ceph_osd_op_w_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_w_latency_count{job=\"$job\"}[1m])),1)",
     "legendFormat": "write"
    },
    {
     "expr": "1000*sum(increase(ceph_osd_op_rw_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_rw_latency_count{job=\"$job\"}[1m])),1)",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_r{job=\"$job\"}[$__interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(ceph_osd_op_w{job=\"$job\"}[$__interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(ceph_osd_op_rw{job=\"$job\"}[$__interval]))",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "MDS Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_mds_reply_latency_sum{job=\"$job\"}/ceph_mds_reply_latency_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "osd count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_osd_op_r_latency_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "osd_latency",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000*(ceph_osd_op_r_latency_sum{job=\"$job\"})/clamp_min(ceph_osd_op_r_latency_count{job=\"$job\"},1)"
    }
   ]
  },
  {
   "title": "Average OSD Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ceph_osd_commit_latency_ms{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Average OSD Apply Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "osd_op_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "1000*(increase(ceph_osd_op_r_latency_count{job=\"$job\"}[1m]))"
    }
   ]
  },
  {
   "title": "osd_op_latency_sum",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "1000*(increase(ceph_osd_op_r_latency_sum{job=\"$job\"}[1m]))"
    }
   ]
  },
  {
   "title": "latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000*(increase(ceph_osd_op_r_latency_sum{job=\"$job\"}[1m]))/clamp_min((increase(ceph_osd_op_r_latency_count{job=\"$job\"}[$__rate_interval])),1)"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "osd status",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_osd_used_bytes{job=\"$job\"}"
    },
    {
     "expr": "ceph_osd_bytes{job=\"$job\"}"
    },
    {
     "expr": "ceph_osd_pgs{job=\"$job\"}",
     "legendFormat": "{{osd}}"
    },
    {
     "expr": "ceph_osd_up{job=\"$job\"}",
     "legendFormat": "{{osd}}"
    },
    {
     "expr": "ceph_osd_in{job=\"$job\"}",
     "legendFormat": "{{osd}}"
    }
   ]
  },
  { "title": "POOL STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "pool",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_pool_pg_num{job=\"$job\"}",
     "legendFormat": "{{osd}}"
    },
    {
     "expr": "ceph_pool_objects_total{job=\"$job\"}",
     "legendFormat": "{{osd}}"
    },
    {
     "expr": "ceph_pool_available_bytes{job=\"$job\"}",
     "legendFormat": "{{osd}}"
    },
    {
     "expr": "ceph_pool_used_bytes{job=\"$job\"}",
     "legendFormat": "{{osd}}"
    }
   ]
  },
  { "title": "RECOVERY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Objects",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_recovery_io_objects", "legendFormat": "Objects" }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_recovery_io_keys", "legendFormat": "Keys" }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_recovery_io_bytes", "legendFormat": "Bytes" }
   ]
  }
 ]
}