{
 "title": "Ceph Server Dashboard",
 "tags": [
  "zabbix",
  "example"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Zabbix Data Source",
    "query": "alexanderzobnin-zabbix-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Host name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Host name" },
     "mode": 2
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "application": { "filter": "General" }, "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "item": { "filter": "System uptime" } }
   ]
  },
  {
   "title": "Required performance, NVPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Zabbix server" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": {
      "filter": "/Required performance of Zabbix server/"
     }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "application": { "filter": "CPU" }, "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "item": { "filter": "/CPU (?!idle)/" } }
   ]
  },
  {
   "title": "Zabbix processes",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 3 },
   "targets": [
    { "application": { "filter": "Zabbix server" }, "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "item": { "filter": "/Zabbix busy/" } }
   ]
  },
  {
   "title": "Zabbix busy processes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "application": { "filter": "Zabbix server" }, "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "item": { "filter": "/Zabbix busy/" } }
   ]
  },
  {
   "title": "Zabbix Queue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "application": { "filter": "Zabbix server" }, "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "item": { "filter": "Zabbix queue" } },
    { "application": { "filter": "Zabbix server" }, "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "item": { "filter": "/Values processed/" } }
   ]
  }
 ]
}