{
 "title": "Libvirt",
 "description": "This is complete dashboard to monitor libvirt hypervisors and virtual machines",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(libvirt_up, instance)"
    }
   },
   {
    "name": "domain",
    "query": {
     "query": "label_values(libvirt_domain_info_vstate{instance=~\"$instance.*\"}, domain)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "query_result(label_replace(libvirt_domain_memory_stats_available, \"service\", \"$1\", \"domain\", \"([a-zA-Z-]*)[0-9]*\"))"
    }
   },
   {
    "name": "job",
    "label": "Cluster",
    "query": {
     "query": "label_values(libvirt_domain_memory_stats_available, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAM and Disk usage on vm",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_available{instance=~\"$instance.*\", job=\"$job\"}",
     "legendFormat": "total"
    },
    {
     "expr": "(libvirt_domain_memory_stats_used_percent{instance=~\"$instance.*\"} * libvirt_domain_memory_stats_available{instance=~\"$instance.*\"}) / 100",
     "legendFormat": "used"
    },
    {
     "expr": "libvirt_domain_memory_stats_used_percent{instance=~\"$instance.*\"}",
     "legendFormat": "used %"
    },
    {
     "expr": "libvirt_domain_block_stats_physicalsize{instance=~\"$instance.*\"}",
     "legendFormat": "Disk Size"
    }
   ]
  },
  {
   "title": "CPU load on physical host",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$instance.*\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "{{instance}} Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$instance.*\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "{{instance}} Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$instance.*\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "{{instance}} Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$instance.*\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "{{instance}} Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$instance.*\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "{{instance}} Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance.*\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "{{instance}} Idle"
    }
   ]
  },
  {
   "title": "FREE memory on physical host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance.*\",job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Stats (by service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used percent",
     "type": "graph",
     "description": "The amount of memory in percent, that used by domain.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_used_percent{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}----({{instance}})"
      }
     ]
    },
    {
     "title": "Total memory inside vm",
     "type": "graph",
     "description": "The total amount of usable memory as seen by the domain. This value may be less than the amount of memory assigned to the domain if a balloon driver is in use or if the guest OS does not initialize all assigned pages. This value is expressed in kB.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_available{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}----({{instance}})"
      }
     ]
    },
    {
     "title": "Available memory inside vm",
     "type": "graph",
     "description": "How much the balloon can be inflated without pushing the guest system to swap, corresponds to 'Available' in /proc/meminfo",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_usable{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}----({{instance}})"
      }
     ]
    },
    {
     "title": "Completely unused memory",
     "type": "graph",
     "description": "The amount of memory left completely unused by the system. Memory that is available but used for reclaimable caches should NOT be reported as free. This value is expressed in kB.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_unused{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Current balloon value",
     "type": "graph",
     "description": "Current balloon value (in KB).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_actual_balloon{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}----({{instance}})"
      }
     ]
    },
    {
     "title": "Cache",
     "type": "graph",
     "description": "The amount of memory, that can be quickly reclaimed without additional I/O (in kB).Typically these pages are used for caching files from disk.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_disk_cache{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}----({{instance}})"
      }
     ]
    },
    {
     "title": "Major fault",
     "type": "graph",
     "description": "Page faults occur when a process makes a valid access to virtual memory that is not available. When servicing the page fault, if disk IO is required, it is considered a major fault.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_major_fault{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}----({{instance}})"
      }
     ]
    },
    {
     "title": "Minor fault",
     "type": "graph",
     "description": "Page faults occur when a process makes a valid access to virtual memory that is not available. When servicing the page not fault, if disk IO is required, it is considered a minor fault.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_minor_fault{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}----({{instance}})"
      }
     ]
    },
    {
     "title": "RSS",
     "type": "graph",
     "description": "Resident Set Size of the process running the domain. This value is in kB",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_rss{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}----({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Stats (by instance and domain)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory used percent",
     "type": "graph",
     "description": "The amount of memory in percent, that used by domain.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_used_percent{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Total memory inside vm",
     "type": "graph",
     "description": "The total amount of usable memory as seen by the domain. This value may be less than the amount of memory assigned to the domain if a balloon driver is in use or if the guest OS does not initialize all assigned pages. This value is expressed in kB.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_available{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Available memory inside vm",
     "type": "graph",
     "description": "How much the balloon can be inflated without pushing the guest system to swap, corresponds to 'Available' in /proc/meminfo",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_usable{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Completely unused memory",
     "type": "graph",
     "description": "The amount of memory left completely unused by the system. Memory that is available but used for reclaimable caches should NOT be reported as free. This value is expressed in kB.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_unused{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Current balloon value",
     "type": "graph",
     "description": "Current balloon value (in KB).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_actual_balloon{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Cache",
     "type": "graph",
     "description": "The amount of memory, that can be quickly reclaimed without additional I/O (in kB).Typically these pages are used for caching files from disk.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_disk_cache{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Major fault",
     "type": "graph",
     "description": "Page faults occur when a process makes a valid access to virtual memory that is not available. When servicing the page fault, if disk IO is required, it is considered a major fault.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_major_fault{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Minor fault",
     "type": "graph",
     "description": "Page faults occur when a process makes a valid access to virtual memory that is not available. When servicing the page not fault, if disk IO is required, it is considered a minor fault.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_minor_fault{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "RSS",
     "type": "graph",
     "description": "Resident Set Size of the process running the domain. This value is in kB",
     "gridPos": { "h": 8, "w": 12, "x": 4, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_rss{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Stats (by service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic",
     "type": "graph",
     "description": "Number of bytes transmitted on a network interface, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(libvirt_domain_interface_stats_transmit_bytes_total{domain=~\"$service.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - transmit"
      },
      {
       "expr": "irate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$service.*\"}[5m])",
       "legendFormat": "{{ domain }} - receive"
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "description": "Number of packets received on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(libvirt_domain_interface_stats_receive_packets_total{domain=~\"$service.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - receive"
      },
      {
       "expr": "rate(libvirt_domain_interface_stats_transmit_packets_total{domain=~\"$service.*\"}[5m])",
       "legendFormat": "{{domain}} - transfer"
      }
     ]
    },
    {
     "title": "Network drops",
     "type": "graph",
     "description": "Number of packet transmit drops on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(libvirt_domain_interface_stats_transmit_drops_total{domain=~\"$service.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - transmit"
      },
      {
       "expr": "rate(libvirt_domain_interface_stats_receive_drops_total{domain=~\"$service.*\"}[5m])",
       "legendFormat": "{{domain}} - receive"
      }
     ]
    },
    {
     "title": "Network Errors",
     "type": "graph",
     "description": "Number of packet receive errors on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(libvirt_domain_interface_stats_receive_errors_total{domain=~\"$service.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - receive"
      },
      {
       "expr": "rate(libvirt_domain_interface_stats_transmit_errors_total{domain=~\"$service.*\"}[5m])",
       "legendFormat": "{{domain}} - transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Stats (by instance and domain)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic",
     "type": "graph",
     "description": "Number of bytes transmitted on a network interface, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(libvirt_domain_interface_stats_transmit_bytes_total{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - transmit"
      },
      {
       "expr": "irate(libvirt_domain_interface_stats_receive_bytes_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
       "legendFormat": "{{ domain }} - receive"
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "description": "Number of packets received on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(libvirt_domain_interface_stats_receive_packets_total{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - receive"
      },
      {
       "expr": "rate(libvirt_domain_interface_stats_transmit_packets_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
       "legendFormat": "{{domain}} - transfer"
      }
     ]
    },
    {
     "title": "Network drops",
     "type": "graph",
     "description": "Number of packet transmit drops on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(libvirt_domain_interface_stats_transmit_drops_total{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - transmit"
      },
      {
       "expr": "rate(libvirt_domain_interface_stats_receive_drops_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
       "legendFormat": "{{domain}} - receive"
      }
     ]
    },
    {
     "title": "Network Errors",
     "type": "graph",
     "description": "Number of packet receive errors on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(libvirt_domain_interface_stats_receive_errors_total{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - receive"
      },
      {
       "expr": "rate(libvirt_domain_interface_stats_transmit_errors_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
       "legendFormat": "{{domain}} - transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Domain Info (by service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virsh defined memory bytes",
     "type": "graph",
     "description": "Maximum allowed memory of the domain, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_info_maximum_memory_bytes{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "description": " Memory usage of the domain, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_info_memory_usage_bytes{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "VCPU count",
     "type": "graph",
     "description": "Number of virtual CPUs for the domain.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_info_virtual_cpus{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "VM state",
     "type": "graph",
     "description": "Virtual domain state. 0: no state, 1: the domain is running, 2: the domain is blocked on resource, 3: the domain is paused by user, 4: the domain is being shut down, 5: the domain is shut off,6: the domain is crashed, 7: the domain is suspended by guest power management",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_info_vstate{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Domain Info (by instance and domain)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virsh defined memory bytes",
     "type": "graph",
     "description": "Maximum allowed memory of the domain, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_info_maximum_memory_bytes{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "description": " Memory usage of the domain, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_info_memory_usage_bytes{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "VCPU count",
     "type": "graph",
     "description": "Number of virtual CPUs for the domain.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_info_virtual_cpus{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "VM state",
     "type": "graph",
     "description": "Virtual domain state. 0: no state, 1: the domain is running, 2: the domain is blocked on resource, 3: the domain is paused by user, 4: the domain is being shut down, 5: the domain is shut off,6: the domain is crashed, 7: the domain is suspended by guest power management",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_info_vstate{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Stats (by service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write and read requests",
     "type": "graph",
     "description": "Number of write requests to a block device.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(libvirt_domain_block_stats_write_requests_total{domain=~\"$service.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - write"
      },
      {
       "expr": "irate(libvirt_domain_block_stats_read_requests_total{domain=~\"$service.*\"}[5m])",
       "legendFormat": "{{domain}} - read"
      }
     ]
    },
    {
     "title": "Write and read time",
     "type": "graph",
     "description": "Total time (ns) spent on writes on a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "irate(libvirt_domain_block_stats_write_time_total{domain=~\"$service.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - write"
      },
      {
       "expr": "irate(libvirt_domain_block_stats_read_time_total{domain=~\"$service.*\"}[5m])",
       "legendFormat": "{{domain}} - read"
      }
     ]
    },
    {
     "title": "Write and read bytes",
     "type": "graph",
     "description": "Number of bytes written to a block device, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(libvirt_domain_block_stats_write_bytes_total{domain=~\"$service.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - write"
      },
      {
       "expr": "irate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$service.*\"}[5m])",
       "legendFormat": "{{ domain }} - read"
      }
     ]
    },
    {
     "title": "Flush requests",
     "type": "graph",
     "description": "Total flush requests from a block device.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(libvirt_domain_block_stats_flush_requests_total{domain=~\"$service.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Physical size of image",
     "type": "graph",
     "description": "Physical size in bytes of the container of the backing image.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_block_stats_physicalsize{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Flush time",
     "type": "graph",
     "description": "Total time (ns) spent on cache flushing to a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "irate(libvirt_domain_block_stats_flush_total{domain=~\"$service.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Image allocation",
     "type": "graph",
     "description": "Offset of the highest written sector on a block device.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_block_stats_allocation{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Logical size of the block device\t",
     "type": "graph",
     "description": "Logical size in bytes of the block device\tbacking image.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_block_stats_capacity{domain=~\"$service.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Stats (by instance and domain)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write and read requests",
     "type": "graph",
     "description": "Number of write requests to a block device.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(libvirt_domain_block_stats_write_requests_total{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - write"
      },
      {
       "expr": "irate(libvirt_domain_block_stats_read_requests_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
       "legendFormat": "{{domain}} - read"
      }
     ]
    },
    {
     "title": "Write and read time",
     "type": "graph",
     "description": "Total time (ns) spent on writes on a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "irate(libvirt_domain_block_stats_write_time_total{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - write"
      },
      {
       "expr": "irate(libvirt_domain_block_stats_read_time_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
       "legendFormat": "{{domain}} - read"
      }
     ]
    },
    {
     "title": "Write and read bytes",
     "type": "graph",
     "description": "Number of bytes written to a block device, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(libvirt_domain_block_stats_write_bytes_total{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}} - write"
      },
      {
       "expr": "irate(libvirt_domain_block_stats_read_bytes_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
       "legendFormat": "{{ domain }} - read"
      }
     ]
    },
    {
     "title": "Flush requests",
     "type": "graph",
     "description": "Total flush requests from a block device.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(libvirt_domain_block_stats_flush_requests_total{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Physical size of image",
     "type": "graph",
     "description": "Physical size in bytes of the container of the backing image.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_block_stats_physicalsize{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Flush time",
     "type": "graph",
     "description": "Total time (ns) spent on cache flushing to a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "irate(libvirt_domain_block_stats_flush_total{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}[5m])",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Image allocation",
     "type": "graph",
     "description": "Offset of the highest written sector on a block device.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_block_stats_allocation{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Logical size of the block device\t",
     "type": "graph",
     "description": "Logical size in bytes of the block device\tbacking image.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "libvirt_domain_block_stats_capacity{instance=~\"$instance.*\", domain=~\"$domain.*\", job=\"$job\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    }
   ]
  }
 ]
}