{
 "title": "OpenStack Exporter",
 "description": "Openstack dashboard using the Openstack Exporter (https://github.com/openstack-exporter/openstack-exporter)",
 "tags": [
  "openstack",
  "openstack-exporter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(openstack_nova_vcpus_used, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nova agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(openstack_nova_agent_state{adminState=\"enabled\", job=\"$cluster\"}[1h]))-sum(last_over_time(openstack_nova_agent_state{adminState=\"enabled\", job=\"$cluster\"}[1h]))"
    }
   ]
  },
  {
   "title": "Nova agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(openstack_nova_agent_state{adminState=\"enabled\", job=\"$cluster\"}[1h])"
    }
   ]
  },
  {
   "title": "Nova agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(openstack_nova_agent_state{adminState=\"enabled\", job=\"$cluster\"}[1h]))"
    }
   ]
  },
  {
   "title": "Cinder agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(last_over_time(openstack_cinder_agent_state{adminState=\"enabled\", job=\"$cluster\"}[1h]))-sum(last_over_time(openstack_cinder_agent_state{adminState=\"enabled\", job=\"$cluster\"}[1h])))"
    }
   ]
  },
  {
   "title": "Cinder agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(openstack_cinder_agent_state{job=\"$cluster\"}[1h])"
    }
   ]
  },
  {
   "title": "Cinder agent up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(openstack_cinder_agent_state{adminState=\"enabled\", job=\"$cluster\"}[1h]))"
    }
   ]
  },
  {
   "title": "Neutron agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(openstack_neutron_agent_state{adminState=\"up\", job=\"$cluster\"}[1h]))-sum(last_over_time(openstack_neutron_agent_state{adminState=\"up\", job=\"$cluster\"}[1h]))"
    }
   ]
  },
  {
   "title": "Neutron agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(openstack_neutron_agent_state{job=\"$cluster\"}[1h])"
    }
   ]
  },
  {
   "title": "Neutron agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(openstack_neutron_agent_state{adminState=\"up\", job=\"$cluster\"}[1h]))"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Overall CPU cores usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_used{job=\"$cluster\"})",
     "legendFormat": "used vcpu cores"
    },
    {
     "expr": "sum(openstack_nova_vcpus_available)",
     "legendFormat": "available vcpu cores"
    }
   ]
  },
  {
   "title": "Overall memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_used_bytes{job=\"$cluster\"})",
     "legendFormat": "used memory"
    },
    {
     "expr": "sum(openstack_nova_memory_available_bytes)",
     "legendFormat": "available memory"
    }
   ]
  },
  {
   "title": "Keystone projects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_identity_projects{job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Glance Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_glance_images{job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nova instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_nova_total_vms{job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Associated, inactive FIPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_neutron_floating_ips_associated_not_active{job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Neutron networks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_neutron_networks{job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Neutron subnets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_neutron_subnets{job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cinder volumes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_cinder_volumes{job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cinder snapshots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_cinder_snapshots{job=\"$cluster\"})"
    }
   ]
  },
  { "title": "Compute nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU core usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "openstack_nova_vcpus_used{job=\"$cluster\"}/(openstack_nova_vcpus_available{job=\"$cluster\"}+openstack_nova_vcpus_used{job=\"$cluster\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "openstack_nova_memory_used_bytes{job=\"$cluster\"}/(openstack_nova_memory_used_bytes{job=\"$cluster\"}+openstack_nova_memory_available_bytes{job=\"$cluster\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Local storage usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "openstack_nova_local_storage_used_bytes{job=\"$cluster\"}/(openstack_nova_local_storage_used_bytes{job=\"$cluster\"}+openstack_nova_local_storage_available_bytes{job=\"$cluster\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Storage nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Volume pool usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(openstack_cinder_pool_capacity_total_gb{job=\"$cluster\"}-openstack_cinder_pool_capacity_free_gb{job=\"$cluster\"})/openstack_cinder_pool_capacity_total_gb{job=\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Volume pool usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_cinder_volume_gb{job=\"$cluster\"}) by (volume_type)",
     "legendFormat": "{{volume_type}}"
    }
   ]
  }
 ]
}