name: basic ci process

on:
  release:
    types: [ "published" ]
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: cd cluster; make generate

    - name: Run validate check
      run: cd cluster; make validate

